version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - graphql-engine
    depends_on:
      - graphql-engine
    environment:
      - CERTBOT_EMAIL=${EMAIL}
      - STAGING=0
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=2048
      - RENEWAL_INTERVAL=8d

  hasura-db:
    image: postgres:12
    volumes:
      - "hasura-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=hasura
    ports:
      - "5432:5432"

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - hasura-db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@hasura-db/hasura
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'

  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000:3000'
    depends_on:
      - graphql-engine
    restart: always
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: ${ADMIN_SECRET}
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://s3.${REGION}.amazonaws.com
      S3_BUCKET: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      AUTO_MIGRATE: 'true'
      PORT: 3000
      HOST:
      AUTH_ENABLE: true
      STORAGE_ENABLE: true
      COOKIE_SECRET:
      JWT_KEY:
      JWT_CLAIMS_NAMESPACE: 'https://hasura.io/jwt/claims'
      JWT_REFRESH_EXPIRES_IN: 43200
      JWT_CUSTOM_FIELDS:
      MAX_REQUESTS: 100
      TIME_FRAME: 900000
      DEFAULT_USER_ROLE: 'user',
      DEFAULT_ANONYMOUS_ROLE: 'anonymous'
      # Sign in
      REGISTRATION_CUSTOM_FIELDS:
      ANONYMOUS_USERS_ENABLE: false
      ALLOW_USER_SELF_DELETE: false
      AUTO_ACTIVATE_NEW_USERS: true
      VERIFY_EMAILS: false
      REDIRECT_URL_SUCCESS:
      REDIRECT_URL_ERROR:
      # IAM Settings
      USER_IMPERSONATION_ENABLE: false
      ALLOWED_EMAIL_DOMAINS:
      CHANGE_EMAIL_ENABLE: true
      LOST_PASSWORD_ENABLE: false
      NOTIFY_EMAIL_CHANGE: false
      MIN_PASSWORD_LENGTH: 3
      HIBP_ENABLE: false
      MFA_ENABLE: true
      OTP_ISSUER: = 'HBP'
      PROVIDER_SUCCESS_REDIRECT:
      PROVIDER_FAILURE_REDIRECT:
      # Github
      GITHUB_ENABLE: false
      GITHUB_CLIENT_ID:
      GITHUB_CLIENT_SECRET:  Optional
      GITHUB_AUTHORIZATION_URL:  Optional
      GITHUB_TOKEN_URL:  Optional
      GITHUB_USER_PROFILE_URL:  Optional
      # Google
      GOOGLE_ENABLE: true
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Facebook
      FACEBOOK_ENABLE: false
      FACEBOOK_CLIENT_ID:
      FACEBOOK_CLIENT_SECRET:
      # Twitter
      TWITTER_ENABLE: false
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      # Linkedin
      LINKEDIN_ENABLE: false
      LINKEDIN_CLIENT_ID:
      LINKEDIN_CLIENT_SECRET:
      # Spotify
      SPOTIFY_ENABLE: false
      SPOTIFY_CLIENT_ID:
      SPOTIFY_CLIENT_SECRET:
      # Apple
      APPLE_ENABLE: false
      APPLE_CLIENT_ID:
      APPLE_TEAM_ID:
      APPLE_KEY_ID:
      APPLE_PRIVATE_KEY:
      # Windows
      WINDOWS_LIVE_ENABLE: false
      WINDOWS_LIVE_CLIENT_ID:
      WINDOWS_LIVE_CLIENT_SECRET:
      # Email
      EMAILS_ENABLE: false
      SMTP_HOST:
      SMTP_PORT: 587
      SMTP_USER:
      SMTP_PASS:
      SMTP_SENDER:
      SMTP_AUTH_METHOD: 'PLAIN'
      SMTP_SECURE: false

volumes:
  hasura-data:
    external: true
