version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
    links:
      - graphql-engine
    depends_on:
      - graphql-engine
    environment:
      - CERTBOT_EMAIL=${EMAIL}
      - STAGING=0
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=2048
      - RENEWAL_INTERVAL=8d

  hasura-db:
    image: postgres:12
    volumes:
      - "hasura-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=hasura
    ports:
      - "5432:5432"

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - hasura-db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@hasura-db/hasura
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'

  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000:3000'
    depends_on:
      - graphql-engine
    restart: always
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: ${ADMIN_SECRET}
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://s3.${REGION}.amazonaws.com
      S3_BUCKET: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      AUTO_MIGRATE: 'true'

volumes:
  hasura-data:
    external: true
